# Generated by Django 4.2.3 on 2023-09-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AHU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('supply_air_temp', models.FloatField()),
                ('heating_setpoint', models.FloatField()),
                ('cooling_setpoint', models.FloatField()),
                ('outdoor_air_temp', models.FloatField()),
                ('mixed_air_temp', models.FloatField()),
                ('return_air_temp', models.FloatField()),
                ('supply_air_fan_status', models.FloatField()),
                ('supply_air_fan_speed', models.FloatField()),
                ('outdoor_air_damper', models.FloatField()),
                ('return_air_damper', models.FloatField()),
                ('exhaust_air_damper', models.FloatField()),
                ('cooling_coil_valve', models.FloatField()),
                ('heating_coil_valve', models.FloatField()),
                ('occupancy_mode', models.FloatField()),
                ('fault_detection', models.FloatField()),
            ],
        ),
    ]
