# Generated by Django 4.2.3 on 2023-09-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_ahu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AHU',
            new_name='value',
        ),
    ]
